notifications:
  slack:
    rooms:
      - baantak:LtnT2T5a5AbrxUpM4FlUUuyl#codeeeeeeeeeeeee
      - egci492:6E7WBO5v99TplnGk0pZFsv8A#bed-management-g

language: python
python:
  - 3.4
  - 3.5

services:
  - sqlite3
  - mysql

install:
  - python scripts/module.py
  - pip install -r requirement.txt

before_script:
  - python scripts/bower.py
  - python scripts/make_and_migrate.py
  - python scripts/collect_static.py
  - python scripts/import_fixture.py

script: python manage.py test
