notifications:
  slack:
    rooms:
      - baantak:LtnT2T5a5AbrxUpM4FlUUuyl#codeeeeeeeeeeeee
      - egci492:6E7WBO5v99TplnGk0pZFsv8A#bed-management-g

language: ruby
rvm:
  - 2.2.4

services:
  - mysql

before_script:
  - mysql -uroot -e 'CREATE DATABASE BedManagement_test'
  - bundle exec rake db:migrate RAILS_ENV=test

script:
  - bundle exec rspec spec/
  - bundle exec rake jasmine:ci