notifications:
  slack:
    rooms:
      - baantak:LtnT2T5a5AbrxUpM4FlUUuyl#codeeeeeeeeeeeee
      - egci492:6E7WBO5v99TplnGk0pZFsv8A#bed-management-g

language: ruby
rvm:
  - 2.2.1

services:
  - mysql